---
Name: dataobject-preview
After:
  - 'framework/*'
  - 'cms/*'
---
PreviewableDataObject:
  extensions:
    - Versioned("Stage","Live")
#ModelAdmin:
#  extra_requirements_javascript:
#    - dataobject-preview/javascript/PDOLeftAndMain.Preview.js
